name: Release

# This workflow is triggered on push events to tags that match the semantic
# version pattern (https://semver.org/). For example, it will trigger on tags
# like v1.2.3, v2.0.0, etc. It should NOT run on pushes to major tags like v1,
# v2, etc. - otherwise the workflow would be at risk of triggering itself.
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    uses: ./.github/workflows/action.yaml
